# Generated by Django 4.1 on 2023-10-29 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('tmdb_id', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
