
name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: bubble
          POSTGRES_PASSWORD: bubble
          POSTGRES_DB: bubble
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.13
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.13
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with Flake8
      run: |
        pip install flake8
        flake8
    - name: Run migrations
      run: python manage.py migrate
      env:
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        APP_ENV: testing
        DB_USER: bubble
        DB_PASSWORD: bubble
        DB_HOST: 127.0.0.1
    - name: Run Tests
      env:
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        APP_ENV: testing
        DB_USER: bubble
        DB_PASSWORD: bubble
        DB_HOST: 127.0.0.1
      run: |
        python manage.py test